version: "3"

services:
  db:
    image: mysql:8.0
    container_name: payments_db
    ports:
      - "3307:3306"
    expose:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sritiman
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: ecommerce_payments
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d
    networks:
      - ecommnet

  ecommerce-backend-payments-api:
    image: ecommerce-backend-payments-api:v1
    container_name: ecommerce-backend-payments-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MYSQL_DATASOURCE_URL=jdbc:mysql://payments_db:3306/ecommerce_payments
    volumes:
      - ~/.gradle:/root/.gradle
    networks:
      - ecommnet
    depends_on:
      - db

volumes:
  my-db:
networks:
  ecommnet:
    external: true