server:
  port: 8081
spring:
  application:
    name: e-commerce-payments
  datasource:
    url: ${MYSQL_DATASOURCE_URL:jdbc:mysql://localhost:3307/ecommerce_payments}
    username: sritiman
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update